#!/bin/bash

#
# Copyright (c) 2017 Parallels International GmbH
#

WAIT_TIMEOUT=3
MAX_RETRIES=20

cat /var/lib/vzupgrade/net_list | grep -v "^Bridged\|^Host-Only\|^Network ID" | while read net vtype device; do
    hwaddr=`grep $device /var/lib/vzupgrade/iflist | awk '{print $5}' `
    echo "Trying to restore network: $net ($vtype : $device : $hwaddr)" | tee -a /var/log/vzupgrade.log
    # Just process all interfaces with given HWaddr
    grep $hwaddr /var/lib/vzupgrade/iflist | cut -f1 -d\  | while read realdev; do
        retry=0
        while [[ $retry < $MAX_RETRIES ]]; do
            sleep $WAIT_TIMEOUT
            prlsrvctl net add $net -i $realdev -t $vtype 2>&1 | tee -a /var/log/vzupgrade.log
            if [ ${PIPESTATUS[0]} != 253 ]; then
                break
            fi
            echo "Waiting for prl-disp..." | tee -a /var/log/vzupgrade.log
            (( retry=$retry+1 ))
        done
    done
done

# Post-processing of VEs
/var/lib/vzupgrade/vzupgrade-post-ves
